import ExplainableCrypto.Helios.Computational.ProofReuse
import ExplainableCrypto.Helios.Computational.Sampling

/-! Two-candidate honest ballots for the swapped abstention/candidate-0
experiment. Every proof is generated by the concrete disjunctive algorithm. -/

namespace ExplainableCrypto.Helios.Computational

variable {F G : Type} [Field F] [AddCommGroup G] [Module F G]

structure HonestCoins (F : Type) where
  nonce : Fin 2 → F
  witness : Fin 3 → F
  challenge : Fin 3 → F
  response : Fin 3 → F

def voteScalar (vote : Bool) : F := if vote then 1 else 0

def proveVote (hash : Hash F G) (g pk : G) (vote : Bool) (r w e z : F) : Proof01 F G :=
  if vote then proveOne hash g pk r w e z else proveZero hash g pk r w e z

theorem proveVote_valid (hash : Hash F G) (g pk : G) (vote : Bool) (r w e z : F) :
    (proveVote hash g pk vote r w e z).Valid hash g pk
      (encryptWith g pk r (voteScalar vote)) := by
  cases vote
  · exact proveZero_valid hash g pk r w e z
  · exact proveOne_valid hash g pk r w e z

def honestBallot (hash : Hash F G) (g pk : G) (vote : Bool)
    (coins : HonestCoins F) : Ballot F G 2 where
  ciphertext := ![encryptWith g pk (coins.nonce 0) (voteScalar vote),
    encryptWith g pk (coins.nonce 1) 0]
  proof := ![proveVote hash g pk vote (coins.nonce 0)
    (coins.witness 0) (coins.challenge 0) (coins.response 0),
    proveZero hash g pk (coins.nonce 1) (coins.witness 1) (coins.challenge 1) (coins.response 1)]
  overall := proveVote hash g pk vote (coins.nonce 0 + coins.nonce 1)
    (coins.witness 2) (coins.challenge 2) (coins.response 2)

theorem encryptWith_add (g pk : G) (r s m t : F) :
    encryptWith g pk r m + encryptWith g pk s t = encryptWith g pk (r + s) (m + t) := by
  ext <;> simp [encryptWith, add_smul, add_comm, add_left_comm, add_assoc]

theorem honestBallot_aggregate (hash : Hash F G) (g pk : G) (vote : Bool)
    (coins : HonestCoins F) :
    (honestBallot hash g pk vote coins).aggregate =
      encryptWith g pk (coins.nonce 0 + coins.nonce 1) (voteScalar vote) := by
  simp [Ballot.aggregate, honestBallot, Fin.sum_univ_two, encryptWith_add]

theorem honestBallot_valid (hash : Hash F G) (g pk : G) (vote : Bool)
    (coins : HonestCoins F) : (honestBallot hash g pk vote coins).Valid hash g pk := by
  constructor
  · intro i
    fin_cases i
    · exact proveVote_valid hash g pk vote _ _ _ _
    · exact proveZero_valid hash g pk _ _ _ _
  · rw [honestBallot_aggregate]
    exact proveVote_valid hash g pk vote _ _ _ _

theorem encryptWith_nonce_eq (g pk : G)
    (hg : Function.Injective (fun r : F => r • g)) {r s m t : F}
    (h : encryptWith g pk r m = encryptWith g pk s t) : r = s := by
  exact hg (congrArg Prod.fst h)

def CollisionFree (left right : HonestCoins F) : Prop :=
  (∀ i j, left.nonce i ≠ right.nonce j) ∧
  (∀ j, left.nonce 0 + left.nonce 1 ≠ right.nonce j)

theorem honestBallot_fresh (hash : Hash F G) (g pk : G)
    (hg : Function.Injective (fun r : F => r • g)) (left right : HonestCoins F)
    (v w : Bool) (h : ∀ i j, left.nonce i ≠ right.nonce j) :
    (honestBallot hash g pk w right).FreshFor [honestBallot hash g pk v left] := by
  intro old ho i j
  simp only [List.mem_singleton] at ho
  subst old
  fin_cases i <;> fin_cases j <;>
    exact fun heq => h _ _ (encryptWith_nonce_eq g pk hg heq.symm)

/-- The smallest enumerated failure: both honest ballots contain the same
zero component when their second nonces agree. Both proofs can still validate. -/
theorem coincident_honest_ballots_not_fresh (hash : Hash F G) (g pk : G)
    (left right : HonestCoins F) (v w : Bool) (h : left.nonce 1 = right.nonce 1) :
    ¬ (honestBallot hash g pk w right).FreshFor [honestBallot hash g pk v left] := by
  intro hf
  apply hf (honestBallot hash g pk v left) (by simp) 1 1
  simp [honestBallot, h]

theorem proofReuse_honest_fresh (hash : Hash F G) (g pk : G)
    (hg : Function.Injective (fun r : F => r • g)) (left right : HonestCoins F)
    (v w : Bool) (e z a : F)
    (hl : ∀ i, left.nonce i ≠ 0) (hr : ∀ i, right.nonce i ≠ 0)
    (hc : CollisionFree left right) :
    (proofReuse hash g pk e z a (honestBallot hash g pk v left)).FreshFor
      [honestBallot hash g pk v left, honestBallot hash g pk w right] := by
  rw [proofReuse_fresh_iff]
  constructor
  · intro old ho j
    simp only [List.mem_cons, List.not_mem_nil, or_false] at ho
    rcases ho with rfl | rfl
    · rw [honestBallot_aggregate]
      fin_cases j
      · intro h
        have heq := encryptWith_nonce_eq g pk hg h
        exact hl 1 (by simpa using heq)
      · intro h
        have heq := encryptWith_nonce_eq g pk hg h
        exact hl 0 (by simpa using heq)
    · rw [honestBallot_aggregate]
      fin_cases j <;> exact fun h => hc.2 _ (encryptWith_nonce_eq g pk hg h)
  · intro old ho j h
    simp only [List.mem_cons, List.not_mem_nil, or_false] at ho
    have hnonce (r m : F) (heq : (0, 0) = encryptWith g pk r m) : r = 0 := by
      apply hg
      simpa [encryptWith] using (congrArg Prod.fst heq).symm
    rcases ho with rfl | rfl
    · fin_cases j <;> exact hl _ (hnonce _ _ h)
    · fin_cases j <;> exact hr _ (hnonce _ _ h)

#print axioms honestBallot_valid
#print axioms honestBallot_fresh
#print axioms coincident_honest_ballots_not_fresh
#print axioms proofReuse_honest_fresh

end ExplainableCrypto.Helios.Computational
