import ExplainableCrypto.Helios.Computational.PrimeHonestTranscriptMachineRun

import ExplainableCrypto.Helios.Computational.PrimeHonestTranscriptMachineSource

namespace ExplainableCrypto.Helios.Computational.PrimeHonestTranscriptControls
open PrimeHonestTranscriptMachine OracleComp OracleSpec BitOracleMachine
attribute [local implicit_reducible] FreeMonoid PFunctor.Idx PFunctor.FreeM.bind
set_option maxRecDepth 262144
set_option maxHeartbeats 0
set_option synthInstance.maxSize 512
private def handler : QueryImpl spec (StateT (List Bool × Nat × Nat) Id) := fun r state =>
  match r with
  | .coin => (state.1.headD false,(state.1.tail,state.2.1+1,state.2.2))
  | .hash w => (w,(state.1,state.2.1,state.2.2+1))
private def replaceRecord (s : Turing.TM2.Stmt (fun _ : Fin 23 => Bool) (Fin 48) (Fin 3)) :=
  let next := ([false,true,true,true,true,false,false,true,false,true] : List Bool).reverse.foldr
    (fun b next => Turing.TM2.Stmt.push 19 (fun _ => b) next) s
  (List.range 10).foldr (fun _ next => Turing.TM2.Stmt.pop 19 (fun v _ => v) next) next
private def mutated (m : Nat) (l : Fin 48) : Command 23 48 3 :=
  if m == 1 && l == 0 then
    match code l with
    | .compute s => .compute (replaceRecord s)
    | c => c
  else if m == 2 && l == 39 then
    match code l with
    | .compute s => .compute (.push 1 (fun _ => true) s)
    | c => c
  else if m == 3 then
    match code l with
    | .coin dest next => .compute (.push dest (fun _ => false) (.goto (fun _ => next)))
    | c => c
  else if m == 4 && l == 0 then
    match code l with
    | .compute s => .compute (.push 17 (fun _ => false) s)
    | c => c
  else if m == 5 && l == 0 then
    match code l with
    | .compute s => .compute (.push 0 (fun _ => false) s)
    | c => c
  else if m == 6 && l == 0 then
    match code l with
    | .compute s => .compute (.push 14 (fun _ => false) s)
    | c => c
  else if m == 7 && l == 0 then
    .compute (.load (fun _ => 0) (.goto (fun _ => sampleLabel 0)))
  else if m == 8 && l == 0 then
    match code l with
    | .compute s => .compute (.push 10 (fun _ => false) s)
    | c => c
  else code l

private def stepView (m : Nat) (cfg : Config) (tape : List Bool) :=
  let out := (simulateQ handler (step (mutated m) cfg)).run (tape,0,0)
  ((out.1.1.l,out.1.1.var.val,List.ofFn out.1.1.stk),out.2.1,out.2.2.1,out.2.2.2,out.1.2)

theorem entry_preserves_reached_state : stepView 0 (⟨some 0,2,![[false,false,false,true],[],[],[],[],[],[true,true,true,false,true],[],[],[],[],[],[],[true],[true,true,true,false,true,false,true,true,true,true,true,false,true,true,false,true,true,true,true,true,true,false,true,true,true,false,true,true,true,true,true,true,false,true,true,true,true,true,true,true,false,false,true,true,true,true,false,true,false,true,true,true,false,false,true,true,true,true,false,true,true,true,true,true,true,false,false,false,true,true,true,true,true,false,false,true,false,true,false,true,true,true,true,false,true,true,false,true,true,false,true,true,true,true,false,true,true,true,false,true],[false,false,true],[false,true],[false,true],[true],[false,true,true,true,true,false,true,true,false,true],[true,false,true],[true,true,true,false,false,true,true],[false,true,false,true]]⟩ : Config) [true,false,true,true,true,false,true] = ((some (1 : Fin 48),0,[[false,false,false,true],[],[],[],[],[],[true,true,true,false,true],[],[],[],[],[],[],[true],[true,true,true,false,true,false,true,true,true,true,true,false,true,true,false,true,true,true,true,true,true,false,true,true,true,false,true,true,true,true,true,true,false,true,true,true,true,true,true,true,false,false,true,true,true,true,false,true,false,true,true,true,false,false,true,true,true,true,false,true,true,true,true,true,true,false,false,false,true,true,true,true,true,false,false,true,false,true,false,true,true,true,true,false,true,true,false,true,true,false,true,true,true,true,false,true,true,true,false,true],[false,false,true],[false,true],[false,true],[true],[false,true,true,true,true,false,true,true,false,true],[true,false,true],[true,true,true,false,false,true,true],[false,true,false,true]]),[true,false,true,true,true,false,true],0,0,3) := by rfl
#print axioms entry_preserves_reached_state

theorem failed_guard_preserves_state_without_query : stepView 0 (⟨some 0,1,![[false,false,false,true],[],[],[],[],[],[true,true,true,false,true],[],[],[],[],[],[],[true],[true,true,true,false,true,false,true,true,true,true,true,false,true,true,false,true,true,true,true,true,true,false,true,true,true,false,true,true,true,true,true,true,false,true,true,true,true,true,true,true,false,false,true,true,true,true,false,true,false,true,true,true,false,false,true,true,true,true,false,true,true,true,true,true,true,false,false,false,true,true,true,true,true,false,false,true,false,true,false,true,true,true,true,false,true,true,false,true,true,false,true,true,true,true,false,true,true,true,false,true],[false,false,true],[false,true],[false,true],[true],[false,true,true,true,true,false,true,true,false,true],[true,false,true],[true,true,true,false,false,true,true],[false,true,false,true]]⟩ : Config) [true,false,true,true,true,false,true] = ((none,1,[[false,false,false,true],[],[],[],[],[],[true,true,true,false,true],[],[],[],[],[],[],[true],[true,true,true,false,true,false,true,true,true,true,true,false,true,true,false,true,true,true,true,true,true,false,true,true,true,false,true,true,true,true,true,true,false,true,true,true,true,true,true,true,false,false,true,true,true,true,false,true,false,true,true,true,false,false,true,true,true,true,false,true,true,true,true,true,true,false,false,false,true,true,true,true,true,false,false,true,false,true,false,true,true,true,true,false,true,true,false,true,true,false,true,true,true,true,false,true,true,true,false,true],[false,false,true],[false,true],[false,true],[true],[false,true,true,true,true,false,true,true,false,true],[true,false,true],[true,true,true,false,false,true,true],[false,true,false,true]]),[true,false,true,true,true,false,true],0,0,3) := by rfl
#print axioms failed_guard_preserves_state_without_query

theorem bypassed_guard_enters_on_failure : stepView 7 (⟨some 0,1,![[false,false,false,true],[],[],[],[],[],[true,true,true,false,true],[],[],[],[],[],[],[true],[true,true,true,false,true,false,true,true,true,true,true,false,true,true,false,true,true,true,true,true,true,false,true,true,true,false,true,true,true,true,true,true,false,true,true,true,true,true,true,true,false,false,true,true,true,true,false,true,false,true,true,true,false,false,true,true,true,true,false,true,true,true,true,true,true,false,false,false,true,true,true,true,true,false,false,true,false,true,false,true,true,true,true,false,true,true,false,true,true,false,true,true,true,true,false,true,true,true,false,true],[false,false,true],[false,true],[false,true],[true],[false,true,true,true,true,false,true,true,false,true],[true,false,true],[true,true,true,false,false,true,true],[false,true,false,true]]⟩ : Config) [true,false,true,true,true,false,true] = ((some (1 : Fin 48),0,[[false,false,false,true],[],[],[],[],[],[true,true,true,false,true],[],[],[],[],[],[],[true],[true,true,true,false,true,false,true,true,true,true,true,false,true,true,false,true,true,true,true,true,true,false,true,true,true,false,true,true,true,true,true,true,false,true,true,true,true,true,true,true,false,false,true,true,true,true,false,true,false,true,true,true,false,false,true,true,true,true,false,true,true,true,true,true,true,false,false,false,true,true,true,true,true,false,false,true,false,true,false,true,true,true,true,false,true,true,false,true,true,false,true,true,true,true,false,true,true,true,false,true],[false,false,true],[false,true],[false,true],[true],[false,true,true,true,true,false,true,true,false,true],[true,false,true],[true,true,true,false,false,true,true],[false,true,false,true]]),[true,false,true,true,true,false,true],0,0,2) := by rfl
#print axioms bypassed_guard_enters_on_failure

theorem wrong_modulus_record_written_at_entry : stepView 1 (⟨some 0,2,![[false,false,false,true],[],[],[],[],[],[true,true,true,false,true],[],[],[],[],[],[],[true],[true,true,true,false,true,false,true,true,true,true,true,false,true,true,false,true,true,true,true,true,true,false,true,true,true,false,true,true,true,true,true,true,false,true,true,true,true,true,true,true,false,false,true,true,true,true,false,true,false,true,true,true,false,false,true,true,true,true,false,true,true,true,true,true,true,false,false,false,true,true,true,true,true,false,false,true,false,true,false,true,true,true,true,false,true,true,false,true,true,false,true,true,true,true,false,true,true,true,false,true],[false,false,true],[false,true],[false,true],[true],[false,true,true,true,true,false,true,true,false,true],[true,false,true],[true,true,true,false,false,true,true],[false,true,false,true]]⟩ : Config) [true,false,true,true,true,false,true] = ((some (1 : Fin 48),0,[[false,false,false,true],[],[],[],[],[],[true,true,true,false,true],[],[],[],[],[],[],[true],[true,true,true,false,true,false,true,true,true,true,true,false,true,true,false,true,true,true,true,true,true,false,true,true,true,false,true,true,true,true,true,true,false,true,true,true,true,true,true,true,false,false,true,true,true,true,false,true,false,true,true,true,false,false,true,true,true,true,false,true,true,true,true,true,true,false,false,false,true,true,true,true,true,false,false,true,false,true,false,true,true,true,true,false,true,true,false,true,true,false,true,true,true,true,false,true,true,true,false,true],[false,false,true],[false,true],[false,true],[true],[false,true,true,true,true,false,false,true,false,true],[true,false,true],[true,true,true,false,false,true,true],[false,true,false,true]]),[true,false,true,true,true,false,true],0,0,23) := by rfl
#print axioms wrong_modulus_record_written_at_entry

theorem corrupted_alpha_at_entry : stepView 4 (⟨some 0,2,![[false,false,false,true],[],[],[],[],[],[true,true,true,false,true],[],[],[],[],[],[],[true],[true,true,true,false,true,false,true,true,true,true,true,false,true,true,false,true,true,true,true,true,true,false,true,true,true,false,true,true,true,true,true,true,false,true,true,true,true,true,true,true,false,false,true,true,true,true,false,true,false,true,true,true,false,false,true,true,true,true,false,true,true,true,true,true,true,false,false,false,true,true,true,true,true,false,false,true,false,true,false,true,true,true,true,false,true,true,false,true,true,false,true,true,true,true,false,true,true,true,false,true],[false,false,true],[false,true],[false,true],[true],[false,true,true,true,true,false,true,true,false,true],[true,false,true],[true,true,true,false,false,true,true],[false,true,false,true]]⟩ : Config) [true,false,true,true,true,false,true] = ((some (1 : Fin 48),0,[[false,false,false,true],[],[],[],[],[],[true,true,true,false,true],[],[],[],[],[],[],[true],[true,true,true,false,true,false,true,true,true,true,true,false,true,true,false,true,true,true,true,true,true,false,true,true,true,false,true,true,true,true,true,true,false,true,true,true,true,true,true,true,false,false,true,true,true,true,false,true,false,true,true,true,false,false,true,true,true,true,false,true,true,true,true,true,true,false,false,false,true,true,true,true,true,false,false,true,false,true,false,true,true,true,true,false,true,true,false,true,true,false,true,true,true,true,false,true,true,true,false,true],[false,false,true],[false,true],[false,false,true],[true],[false,true,true,true,true,false,true,true,false,true],[true,false,true],[true,true,true,false,false,true,true],[false,true,false,true]]),[true,false,true,true,true,false,true],0,0,4) := by rfl
#print axioms corrupted_alpha_at_entry

theorem corrupted_beta_at_entry : stepView 5 (⟨some 0,2,![[false,false,false,true],[],[],[],[],[],[true,true,true,false,true],[],[],[],[],[],[],[true],[true,true,true,false,true,false,true,true,true,true,true,false,true,true,false,true,true,true,true,true,true,false,true,true,true,false,true,true,true,true,true,true,false,true,true,true,true,true,true,true,false,false,true,true,true,true,false,true,false,true,true,true,false,false,true,true,true,true,false,true,true,true,true,true,true,false,false,false,true,true,true,true,true,false,false,true,false,true,false,true,true,true,true,false,true,true,false,true,true,false,true,true,true,true,false,true,true,true,false,true],[false,false,true],[false,true],[false,true],[true],[false,true,true,true,true,false,true,true,false,true],[true,false,true],[true,true,true,false,false,true,true],[false,true,false,true]]⟩ : Config) [true,false,true,true,true,false,true] = ((some (1 : Fin 48),0,[[false,false,false,false,true],[],[],[],[],[],[true,true,true,false,true],[],[],[],[],[],[],[true],[true,true,true,false,true,false,true,true,true,true,true,false,true,true,false,true,true,true,true,true,true,false,true,true,true,false,true,true,true,true,true,true,false,true,true,true,true,true,true,true,false,false,true,true,true,true,false,true,false,true,true,true,false,false,true,true,true,true,false,true,true,true,true,true,true,false,false,false,true,true,true,true,true,false,false,true,false,true,false,true,true,true,true,false,true,true,false,true,true,false,true,true,true,true,false,true,true,true,false,true],[false,false,true],[false,true],[false,true],[true],[false,true,true,true,true,false,true,true,false,true],[true,false,true],[true,true,true,false,false,true,true],[false,true,false,true]]),[true,false,true,true,true,false,true],0,0,4) := by rfl
#print axioms corrupted_beta_at_entry

theorem corrupted_context_at_entry : stepView 6 (⟨some 0,2,![[false,false,false,true],[],[],[],[],[],[true,true,true,false,true],[],[],[],[],[],[],[true],[true,true,true,false,true,false,true,true,true,true,true,false,true,true,false,true,true,true,true,true,true,false,true,true,true,false,true,true,true,true,true,true,false,true,true,true,true,true,true,true,false,false,true,true,true,true,false,true,false,true,true,true,false,false,true,true,true,true,false,true,true,true,true,true,true,false,false,false,true,true,true,true,true,false,false,true,false,true,false,true,true,true,true,false,true,true,false,true,true,false,true,true,true,true,false,true,true,true,false,true],[false,false,true],[false,true],[false,true],[true],[false,true,true,true,true,false,true,true,false,true],[true,false,true],[true,true,true,false,false,true,true],[false,true,false,true]]⟩ : Config) [true,false,true,true,true,false,true] = ((some (1 : Fin 48),0,[[false,false,false,true],[],[],[],[],[],[true,true,true,false,true],[],[],[],[],[],[],[true],[false,true,true,true,false,true,false,true,true,true,true,true,false,true,true,false,true,true,true,true,true,true,false,true,true,true,false,true,true,true,true,true,true,false,true,true,true,true,true,true,true,false,false,true,true,true,true,false,true,false,true,true,true,false,false,true,true,true,true,false,true,true,true,true,true,true,false,false,false,true,true,true,true,true,false,false,true,false,true,false,true,true,true,true,false,true,true,false,true,true,false,true,true,true,true,false,true,true,true,false,true],[false,false,true],[false,true],[false,true],[true],[false,true,true,true,true,false,true,true,false,true],[true,false,true],[true,true,true,false,false,true,true],[false,true,false,true]]),[true,false,true,true,true,false,true],0,0,4) := by rfl
#print axioms corrupted_context_at_entry

theorem corrupted_saved_word_at_entry : stepView 8 (⟨some 0,2,![[false,false,false,true],[],[],[],[],[],[true,true,true,false,true],[],[],[],[],[],[],[true],[true,true,true,false,true,false,true,true,true,true,true,false,true,true,false,true,true,true,true,true,true,false,true,true,true,false,true,true,true,true,true,true,false,true,true,true,true,true,true,true,false,false,true,true,true,true,false,true,false,true,true,true,false,false,true,true,true,true,false,true,true,true,true,true,true,false,false,false,true,true,true,true,true,false,false,true,false,true,false,true,true,true,true,false,true,true,false,true,true,false,true,true,true,true,false,true,true,true,false,true],[false,false,true],[false,true],[false,true],[true],[false,true,true,true,true,false,true,true,false,true],[true,false,true],[true,true,true,false,false,true,true],[false,true,false,true]]⟩ : Config) [true,false,true,true,true,false,true] = ((some (1 : Fin 48),0,[[false,false,false,true],[],[],[],[],[],[true,true,true,false,true],[],[],[],[false],[],[],[true],[true,true,true,false,true,false,true,true,true,true,true,false,true,true,false,true,true,true,true,true,true,false,true,true,true,false,true,true,true,true,true,true,false,true,true,true,true,true,true,true,false,false,true,true,true,true,false,true,false,true,true,true,false,false,true,true,true,true,false,true,true,true,true,true,true,false,false,false,true,true,true,true,true,false,false,true,false,true,false,true,true,true,true,false,true,true,false,true,true,false,true,true,true,true,false,true,true,true,false,true],[false,false,true],[false,true],[false,true],[true],[false,true,true,true,true,false,true,true,false,true],[true,false,true],[true,true,true,false,false,true,true],[false,true,false,true]]),[true,false,true,true,true,false,true],0,0,4) := by rfl
#print axioms corrupted_saved_word_at_entry

theorem fixed_coin_instruction_skips_query : mutated 3 36 =
    .compute (.push 5 (fun _ => false) (.goto (fun _ => 37))) := by rfl
#print axioms fixed_coin_instruction_skips_query

end ExplainableCrypto.Helios.Computational.PrimeHonestTranscriptControls
namespace ExplainableCrypto.Helios.Computational.PrimeHonestTranscriptControls
open PrimeHonestTranscriptMachine OracleComp OracleSpec BitOracleMachine
attribute [local implicit_reducible] FreeMonoid PFunctor.Idx PFunctor.FreeM.bind
set_option maxRecDepth 8192
private def runHandler : QueryImpl spec (StateT (List Bool × Nat × Nat) Id) := fun r state =>
  match r with
  | .coin => (state.1.headD false,(state.1.tail,state.2.1+1,state.2.2))
  | .hash w => (w,(state.1,state.2.1,state.2.2+1))
private def runView (fuel : Nat) (cfg : Config) (tape : List Bool) :=
  let out := (simulateQ runHandler (Prod.fst <$> BitOracleMachine.run code fuel cfg)).run (tape,0,0)
  ((out.1.l,out.1.var.val,List.ofFn out.1.stk),out.2.1,out.2.2.1,out.2.2.2)

/-- Literal expected frame and coins come from the independent Python fixture;
the checked execution theorem reduces the original run to its small coin tree. -/
theorem zero_full_run : runView (clock 0 2) (⟨some 0,2,![[false,false,true],[],[],[],[],[],[true,false,true],[],[],[],[],[],[],[true],[true,true,true,false,true,false,true,true,true,true,false,true,true,true,true,true,true,false,true,false,true,true,true,true,true,true,false,true,true,false,true,true,true,true,false,false,true,true,true,true,false,true,true,true,true,true,true,false,false,false,true,true,true,false,true,true,true,false,true,true,true,true,false,false,true,true,false,true,true,false,false,true,true,false,true,true,true,true,false,true,true,true,false,true],[true],[false,false,true],[false,false,true],[true],[false,true,true,false,false,true],[true,false,true],[true,false,true],[true]]⟩ : Config) [false,false,true,false,true] =
    ((none,2,[[false,false,true],[],[false,true],[],[],[],[true,false,true],[false],[],[],[],[],[],[true],[true,true,true,false,true,false,true,true,true,true,false,true,true,true,true,true,true,false,true,false,true,true,true,true,true,true,false,true,true,false,true,true,true,true,false,false,true,true,true,true,false,true,true,true,true,true,true,false,false,false,true,true,true,false,true,true,true,false,true,true,true,true,false,false,true,true,false,true,true,false,false,true,true,false,true,true,true,true,false,true,true,true,false,true],[true],[false,false,true],[false,false,true],[true],[false,true,true,false,false,true],[true,false,true],[true,false,true],[true]]),[true,false,true],2,0) := by
  obtain ⟨charge,hc,he⟩ := charged 0 2 (by decide) [false,false,true] [false,false,true] [true] [true,false,true] [true,false,true] [true] [true,true,true,false,true,false,true,true,true,true,false,true,true,true,true,true,true,false,true,false,true,true,true,true,true,true,false,true,true,false,true,true,true,true,false,false,true,true,true,true,false,true,true,true,true,true,true,false,false,false,true,true,true,false,true,true,true,false,true,true,true,true,false,false,true,true,false,true,true,false,false,true,true,false,true,true,true,true,false,true,true,true,false,true] [true,false,true] [false,false,true] [true] true ![[],[],[]]
  have hi : (⟨some 0,2,![[false,false,true],[],[],[],[],[],[true,false,true],[],[],[],[],[],[],[true],[true,true,true,false,true,false,true,true,true,true,false,true,true,true,true,true,true,false,true,false,true,true,true,true,true,true,false,true,true,false,true,true,true,true,false,false,true,true,true,true,false,true,true,true,true,true,true,false,false,false,true,true,true,false,true,true,true,false,true,true,true,true,false,false,true,true,false,true,true,false,false,true,true,false,true,true,true,true,false,true,true,true,false,true],[true],[false,false,true],[false,false,true],[true],[false,true,true,false,false,true],[true,false,true],[true,false,true],[true]]⟩ : Config) = start [false,false,true] [false,false,true] [true] (SamplerOperands.input 0 2 []) [true,false,true] [true,false,true] [true] [true,true,true,false,true,false,true,true,true,true,false,true,true,true,true,true,true,false,true,false,true,true,true,true,true,true,false,true,true,false,true,true,true,true,false,false,true,true,true,true,false,true,true,true,true,true,true,false,false,false,true,true,true,false,true,true,true,false,true,true,true,true,false,false,true,true,false,true,true,false,false,true,true,false,true,true,true,true,false,true,true,true,false,true] [true,false,true] [false,false,true] [true] true ![[],[],[]] := by rfl
  rw [hi]
  dsimp only [runView]
  rw [he]
  simp only [Functor.map_map]
  rfl
#print axioms zero_full_run

/-- Literal expected frame and coins come from the independent Python fixture;
the checked execution theorem reduces the original run to its small coin tree. -/
theorem distinct_full_run : runView (clock 0 11) (⟨some 0,2,![[false,false,false,true],[],[],[],[],[],[true,true,true,false,true],[],[],[],[true,false,true],[false,true,true],[true,true,false],[true],[true,true,true,false,true,false,true,true,true,true,true,false,true,true,false,true,true,true,true,true,true,false,true,true,true,false,true,true,true,true,true,true,false,true,true,true,true,true,true,true,false,false,true,true,true,true,false,true,false,true,true,true,false,false,true,true,true,true,false,true,true,true,true,true,true,false,false,false,true,true,true,true,true,false,false,true,false,true,false,true,true,true,true,false,true,true,false,true,true,false,true,true,true,true,false,true,true,true,false,true],[false,false,true],[false,true],[false,true],[true],[false,true,true,true,true,false,true,true,false,true],[true,false,true],[true,true,true,false,false,true,true],[false,true,false,true]]⟩ : Config) [true,false,true,true,true,false,true] =
    ((none,2,[[false,false,false,true],[],[true,true,false,true],[],[],[],[true,true,true,false,true],[true,true,false,false,true],[],[],[true,false,true],[false,true,true],[true,true,false],[true],[true,true,true,false,true,false,true,true,true,true,true,false,true,true,false,true,true,true,true,true,true,false,true,true,true,false,true,true,true,true,true,true,false,true,true,true,true,true,true,true,false,false,true,true,true,true,false,true,false,true,true,true,false,false,true,true,true,true,false,true,true,true,true,true,true,false,false,false,true,true,true,true,true,false,false,true,false,true,false,true,true,true,true,false,true,true,false,true,true,false,true,true,true,true,false,true,true,true,false,true],[false,false,true],[false,true],[false,true],[true],[false,true,true,true,true,false,true,true,false,true],[true,false,true],[true,true,true,false,false,true,true],[false,true,false,true]]),[true,false,true],4,0) := by
  obtain ⟨charge,hc,he⟩ := charged 0 11 (by decide) [false,true] [false,false,false,true] [true] [true,false,true] [true,true,true,false,false,true,true] [false,true,false,true] [true,true,true,false,true,false,true,true,true,true,true,false,true,true,false,true,true,true,true,true,true,false,true,true,true,false,true,true,true,true,true,true,false,true,true,true,true,true,true,true,false,false,true,true,true,true,false,true,false,true,true,true,false,false,true,true,true,true,false,true,true,true,true,true,true,false,false,false,true,true,true,true,true,false,false,true,false,true,false,true,true,true,true,false,true,true,false,true,true,false,true,true,true,true,false,true,true,true,false,true] [true,true,true,false,true] [false,true] [false,false,true] true ![[true,false,true],[false,true,true],[true,true,false]]
  have hi : (⟨some 0,2,![[false,false,false,true],[],[],[],[],[],[true,true,true,false,true],[],[],[],[true,false,true],[false,true,true],[true,true,false],[true],[true,true,true,false,true,false,true,true,true,true,true,false,true,true,false,true,true,true,true,true,true,false,true,true,true,false,true,true,true,true,true,true,false,true,true,true,true,true,true,true,false,false,true,true,true,true,false,true,false,true,true,true,false,false,true,true,true,true,false,true,true,true,true,true,true,false,false,false,true,true,true,true,true,false,false,true,false,true,false,true,true,true,true,false,true,true,false,true,true,false,true,true,true,true,false,true,true,true,false,true],[false,false,true],[false,true],[false,true],[true],[false,true,true,true,true,false,true,true,false,true],[true,false,true],[true,true,true,false,false,true,true],[false,true,false,true]]⟩ : Config) = start [false,true] [false,false,false,true] [true] (SamplerOperands.input 0 11 []) [true,false,true] [true,true,true,false,false,true,true] [false,true,false,true] [true,true,true,false,true,false,true,true,true,true,true,false,true,true,false,true,true,true,true,true,true,false,true,true,true,false,true,true,true,true,true,true,false,true,true,true,true,true,true,true,false,false,true,true,true,true,false,true,false,true,true,true,false,false,true,true,true,true,false,true,true,true,true,true,true,false,false,false,true,true,true,true,true,false,false,true,false,true,false,true,true,true,true,false,true,true,false,true,true,false,true,true,true,true,false,true,true,true,false,true] [true,true,true,false,true] [false,true] [false,false,true] true ![[true,false,true],[false,true,true],[true,true,false]] := by rfl
  rw [hi]
  dsimp only [runView]
  rw [he]
  simp only [Functor.map_map]
  rfl
#print axioms distinct_full_run

end ExplainableCrypto.Helios.Computational.PrimeHonestTranscriptControls
