import ExplainableCrypto.Helios.Computational.PrimeSimAllCommitCallerSource

/-! Independent complete results pin all four actual commitment coordinates,
intermediate d/gamma, every retained word and cleaned workspace. Tail execution
uses its checked source law; no full raw-native campaign is claimed here. -/
namespace ExplainableCrypto.Helios.Computational.PrimeSimAllCommitControls
open OracleComp BitOracleMachine
set_option maxRecDepth 262144
set_option maxHeartbeats 400000
attribute [local irreducible] BitOracleMachine.run
instance : Fact (Nat.Prime 3) := ⟨by decide⟩
instance : Fact (Nat.Prime 7) := ⟨by decide⟩
private def g : PrimeGroup 7 3 := Additive.ofMul
  (rootsOfUnity.mkOfPowEq (2 : ZMod 7) (by decide : (2 : ZMod 7)^3 = 1))
private def pk : PrimeGroup 7 3 := Additive.ofMul
  (rootsOfUnity.mkOfPowEq (4 : ZMod 7) (by decide : (4 : ZMod 7)^3 = 1))

theorem q3_true_distinct_tail :
    Prod.fst <$> BitOracleMachine.run PrimeSimOneTail.code (PrimeSimOneTail.clock 7 3)
      (PrimeSimOneTail.start ![[true],[true,true,false,false,true],[true,true],[true],[],[],[true,true,true],[true,true,false,false,true],[],[],[false],[true,false,true],[true,false,true],[true],[true,true,true,false,true,false,true,true,true,true,false,true,true,true,true,true,true,false,true,true,true,true,true,true,true,true,false,true,true,true,true,true,true,true,false,false,true,true,true,true,false,true,false,true,true,true,false,false,true,true,true,true,false,true,true,true,true,true,true,false,false,false,true,true,true,true,false,false,true,true,false,true,true,false,true,true,true,false,true,true,true,true,false,true,true,true,false,true],[false,false,true],[false,true],[false,true],[true],[false,true,true,false,true,true],[true,false,true],[true,true,false,false,true],[false,true],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[false,false,true]]) =
    pure (⟨none,2,![[true],[true,true,false,false,true],[true,true],[true],[],[],[true,true,true],[true,true,false,false,true],[],[],[false],[true,false,true],[true,false,true],[true],[true,true,true,false,true,false,true,true,true,true,false,true,true,true,true,true,true,false,true,true,true,true,true,true,true,true,false,true,true,true,true,true,true,true,false,false,true,true,true,true,false,true,false,true,true,true,false,false,true,true,true,true,false,true,true,true,true,true,true,false,false,false,true,true,true,true,false,false,true,true,false,true,true,false,true,true,true,false,true,true,true,true,false,true,true,true,false,true],[false,false,true],[false,true],[false,true],[true],[false,true,true,false,true,true],[true,false,true],[true,true,false,false,true],[false,true],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[false,false,true],[false,false,true],[true],[],[true]]⟩ : PrimeSimOneTail.Config) := by
  have hi : (PrimeSimDifferenceMachine.sourceResult 0 g pk true [true,false,true] (((1 : ZMod 3),2),(0,1,1,2))).stk = ![[true],[true,true,false,false,true],[true,true],[true],[],[],[true,true,true],[true,true,false,false,true],[],[],[false],[true,false,true],[true,false,true],[true],[true,true,true,false,true,false,true,true,true,true,false,true,true,true,true,true,true,false,true,true,true,true,true,true,true,true,false,true,true,true,true,true,true,true,false,false,true,true,true,true,false,true,false,true,true,true,false,false,true,true,true,true,false,true,true,true,true,true,true,false,false,false,true,true,true,true,false,false,true,true,false,true,true,false,true,true,true,false,true,true,true,true,false,true,true,true,false,true],[false,false,true],[false,true],[false,true],[true],[false,true,true,false,true,true],[true,false,true],[true,true,false,false,true],[false,true],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[false,false,true]] := by decide +kernel
  have ho : PrimeSimOneTail.sourceResult 0 g pk true [true,false,true] (((1 : ZMod 3),2),(0,1,1,2)) = (⟨none,2,![[true],[true,true,false,false,true],[true,true],[true],[],[],[true,true,true],[true,true,false,false,true],[],[],[false],[true,false,true],[true,false,true],[true],[true,true,true,false,true,false,true,true,true,true,false,true,true,true,true,true,true,false,true,true,true,true,true,true,true,true,false,true,true,true,true,true,true,true,false,false,true,true,true,true,false,true,false,true,true,true,false,false,true,true,true,true,false,true,true,true,true,true,true,false,false,false,true,true,true,true,false,false,true,true,false,true,true,false,true,true,true,false,true,true,true,true,false,true,true,true,false,true],[false,false,true],[false,true],[false,true],[true],[false,true,true,false,true,true],[true,false,true],[true,true,false,false,true],[false,true],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[false,false,true],[false,false,true],[true],[],[true]]⟩ : PrimeSimOneTail.Config) := by
    change (⟨_,_,_⟩ : PrimeSimOneTail.Config) = ⟨_,_,_⟩
    congr 1; funext k; fin_cases k <;> decide +kernel
  simpa only [hi,ho] using PrimeSimOneTail.source 0 g pk true [true,false,true] (((1 : ZMod 3),2),(0,1,1,2))

/-- Complete result interpretation for the raw caller's checked source tree. -/
theorem q3_true_distinct_raw_result :
    PrimeSimAllCommitCaller.sourceResult 0 g pk true [true,false,true] (((1 : ZMod 3),2),(0,1,1,2)) = (⟨none,2,![[true],[true,true,false,false,true],[true,true],[true],[],[],[true,true,true],[true,true,false,false,true],[],[],[false],[true,false,true],[true,false,true],[true],[true,true,true,false,true,false,true,true,true,true,false,true,true,true,true,true,true,false,true,true,true,true,true,true,true,true,false,true,true,true,true,true,true,true,false,false,true,true,true,true,false,true,false,true,true,true,false,false,true,true,true,true,false,true,true,true,true,true,true,false,false,false,true,true,true,true,false,false,true,true,false,true,true,false,true,true,true,false,true,true,true,true,false,true,true,true,false,true],[false,false,true],[false,true],[false,true],[true],[false,true,true,false,true,true],[true,false,true],[true,true,false,false,true],[false,true],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[false,false,true],[false,false,true],[true],[],[true]]⟩ : PrimeSimAllCommitCaller.Config) := by
  change (⟨_,_,_⟩ : PrimeSimAllCommitCaller.Config) = ⟨_,_,_⟩
  congr 1; funext k; fin_cases k <;> decide +kernel
#print axioms q3_true_distinct_tail
#print axioms q3_true_distinct_raw_result

theorem q3_false_distinct_tail :
    Prod.fst <$> BitOracleMachine.run PrimeSimOneTail.code (PrimeSimOneTail.clock 7 3)
      (PrimeSimOneTail.start ![[false,false,true],[true,true,false,false,true],[true,true],[false,true],[],[],[true,true,true],[true,true,false,false,true],[],[],[false],[true,false,true],[true,true,false,false,true],[true],[true,true,true,false,true,false,true,true,true,true,false,true,true,true,true,true,true,false,true,true,true,true,true,true,true,true,false,true,true,true,true,true,true,true,false,false,true,true,true,true,false,true,false,true,true,true,false,false,true,true,true,true,false,true,true,true,true,true,true,false,false,false,true,true,true,true,false,false,true,true,false,true,true,false,true,true,true,false,true,false,true,true,false,true,true,true,false,true],[false,false,true],[false,true],[false,true],[false],[false,true,true,false,true,true],[true,false,true],[true,true,false,false,true],[false,true],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[false,false,true]]) =
    pure (⟨none,2,![[false,false,true],[true,true,false,false,true],[true,true],[false,true],[],[],[true,true,true],[true,true,false,false,true],[],[],[false],[true,false,true],[true,true,false,false,true],[true],[true,true,true,false,true,false,true,true,true,true,false,true,true,true,true,true,true,false,true,true,true,true,true,true,true,true,false,true,true,true,true,true,true,true,false,false,true,true,true,true,false,true,false,true,true,true,false,false,true,true,true,true,false,true,true,true,true,true,true,false,false,false,true,true,true,true,false,false,true,true,false,true,true,false,true,true,true,false,true,false,true,true,false,true,true,true,false,true],[false,false,true],[false,true],[false,true],[false],[false,true,true,false,true,true],[true,false,true],[true,true,false,false,true],[false,true],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[false,false,true],[false,true],[true],[],[false,false,true]]⟩ : PrimeSimOneTail.Config) := by
  have hi : (PrimeSimDifferenceMachine.sourceResult 0 g pk false [true,false,true] (((1 : ZMod 3),2),(0,1,2,2))).stk = ![[false,false,true],[true,true,false,false,true],[true,true],[false,true],[],[],[true,true,true],[true,true,false,false,true],[],[],[false],[true,false,true],[true,true,false,false,true],[true],[true,true,true,false,true,false,true,true,true,true,false,true,true,true,true,true,true,false,true,true,true,true,true,true,true,true,false,true,true,true,true,true,true,true,false,false,true,true,true,true,false,true,false,true,true,true,false,false,true,true,true,true,false,true,true,true,true,true,true,false,false,false,true,true,true,true,false,false,true,true,false,true,true,false,true,true,true,false,true,false,true,true,false,true,true,true,false,true],[false,false,true],[false,true],[false,true],[false],[false,true,true,false,true,true],[true,false,true],[true,true,false,false,true],[false,true],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[false,false,true]] := by decide +kernel
  have ho : PrimeSimOneTail.sourceResult 0 g pk false [true,false,true] (((1 : ZMod 3),2),(0,1,2,2)) = (⟨none,2,![[false,false,true],[true,true,false,false,true],[true,true],[false,true],[],[],[true,true,true],[true,true,false,false,true],[],[],[false],[true,false,true],[true,true,false,false,true],[true],[true,true,true,false,true,false,true,true,true,true,false,true,true,true,true,true,true,false,true,true,true,true,true,true,true,true,false,true,true,true,true,true,true,true,false,false,true,true,true,true,false,true,false,true,true,true,false,false,true,true,true,true,false,true,true,true,true,true,true,false,false,false,true,true,true,true,false,false,true,true,false,true,true,false,true,true,true,false,true,false,true,true,false,true,true,true,false,true],[false,false,true],[false,true],[false,true],[false],[false,true,true,false,true,true],[true,false,true],[true,true,false,false,true],[false,true],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[false,false,true],[false,true],[true],[],[false,false,true]]⟩ : PrimeSimOneTail.Config) := by
    change (⟨_,_,_⟩ : PrimeSimOneTail.Config) = ⟨_,_,_⟩
    congr 1; funext k; fin_cases k <;> decide +kernel
  simpa only [hi,ho] using PrimeSimOneTail.source 0 g pk false [true,false,true] (((1 : ZMod 3),2),(0,1,2,2))

/-- Complete result interpretation for the raw caller's checked source tree. -/
theorem q3_false_distinct_raw_result :
    PrimeSimAllCommitCaller.sourceResult 0 g pk false [true,false,true] (((1 : ZMod 3),2),(0,1,2,2)) = (⟨none,2,![[false,false,true],[true,true,false,false,true],[true,true],[false,true],[],[],[true,true,true],[true,true,false,false,true],[],[],[false],[true,false,true],[true,true,false,false,true],[true],[true,true,true,false,true,false,true,true,true,true,false,true,true,true,true,true,true,false,true,true,true,true,true,true,true,true,false,true,true,true,true,true,true,true,false,false,true,true,true,true,false,true,false,true,true,true,false,false,true,true,true,true,false,true,true,true,true,true,true,false,false,false,true,true,true,true,false,false,true,true,false,true,true,false,true,true,true,false,true,false,true,true,false,true,true,true,false,true],[false,false,true],[false,true],[false,true],[false],[false,true,true,false,true,true],[true,false,true],[true,true,false,false,true],[false,true],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[false,false,true],[false,true],[true],[],[false,false,true]]⟩ : PrimeSimAllCommitCaller.Config) := by
  change (⟨_,_,_⟩ : PrimeSimAllCommitCaller.Config) = ⟨_,_,_⟩
  congr 1; funext k; fin_cases k <;> decide +kernel
#print axioms q3_false_distinct_tail
#print axioms q3_false_distinct_raw_result
end ExplainableCrypto.Helios.Computational.PrimeSimAllCommitControls
