import ExplainableCrypto.Helios.Computational.PrimeSimDifferenceMachineSource

namespace ExplainableCrypto.Helios.Computational.PrimeSimDifferenceControls
open PrimeSimDifferenceMachine OracleComp BitOracleMachine
set_option maxRecDepth 262144
set_option maxHeartbeats 400000
attribute [local irreducible] BitOracleMachine.run
instance : Fact (Nat.Prime 3) := ⟨by decide⟩
instance : Fact (Nat.Prime 7) := ⟨by decide⟩
private def g : PrimeGroup 7 3 := Additive.ofMul
  (rootsOfUnity.mkOfPowEq (2 : ZMod 7) (by decide : (2 : ZMod 7)^3 = 1))
private def pk : PrimeGroup 7 3 := Additive.ofMul
  (rootsOfUnity.mkOfPowEq (4 : ZMod 7) (by decide : (4 : ZMod 7)^3 = 1))

/-- Independent complete-state underflow fixture retains both commitments,
all original prefixes and private context while adding the canonical d prefix. -/
theorem q3_true_distinct_full_state :
    Prod.fst <$> BitOracleMachine.run code (clock 3) (start ![[true],[],[true,true],[true],[],[],[true,true,true],[true,true,false,false,true],[],[],[false],[true,false,true],[true,false,true],[true],[true,true,true,false,true,false,true,true,true,true,false,true,true,true,true,true,true,false,true,true,true,true,true,true,true,true,false,true,true,true,true,true,true,true,false,false,true,true,true,true,false,true,false,true,true,true,false,false,true,true,true,true,false,true,true,true,true,true,true,false,false,false,true,true,true,true,false,false,true,true,false,true,true,false,true,true,true,false,true,true,true,true,false,true,true,true,false,true],[false,false,true],[false,true],[false,true],[true],[false,true,true,false,true,true],[true,false,true],[true,true,false,false,true],[false,true],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[false,false,true]]) =
      pure (⟨none,2,![[true],[true,true,false,false,true],[true,true],[true],[],[],[true,true,true],[true,true,false,false,true],[],[],[false],[true,false,true],[true,false,true],[true],[true,true,true,false,true,false,true,true,true,true,false,true,true,true,true,true,true,false,true,true,true,true,true,true,true,true,false,true,true,true,true,true,true,true,false,false,true,true,true,true,false,true,false,true,true,true,false,false,true,true,true,true,false,true,true,true,true,true,true,false,false,false,true,true,true,true,false,false,true,true,false,true,true,false,true,true,true,false,true,true,true,true,false,true,true,true,false,true],[false,false,true],[false,true],[false,true],[true],[false,true,true,false,true,true],[true,false,true],[true,true,false,false,true],[false,true],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[false,false,true]]⟩ : Config) := by
  have hi : (PrimeSimCommitPairCaller.sourceResult 0 g pk true [true,false,true] (((1 : ZMod 3),2),(0,1,1,2))).stk = ![[true],[],[true,true],[true],[],[],[true,true,true],[true,true,false,false,true],[],[],[false],[true,false,true],[true,false,true],[true],[true,true,true,false,true,false,true,true,true,true,false,true,true,true,true,true,true,false,true,true,true,true,true,true,true,true,false,true,true,true,true,true,true,true,false,false,true,true,true,true,false,true,false,true,true,true,false,false,true,true,true,true,false,true,true,true,true,true,true,false,false,false,true,true,true,true,false,false,true,true,false,true,true,false,true,true,true,false,true,true,true,true,false,true,true,true,false,true],[false,false,true],[false,true],[false,true],[true],[false,true,true,false,true,true],[true,false,true],[true,true,false,false,true],[false,true],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[false,false,true]] := by decide +kernel
  have ho : sourceResult 0 g pk true [true,false,true] (((1 : ZMod 3),2),(0,1,1,2)) = (⟨none,2,![[true],[true,true,false,false,true],[true,true],[true],[],[],[true,true,true],[true,true,false,false,true],[],[],[false],[true,false,true],[true,false,true],[true],[true,true,true,false,true,false,true,true,true,true,false,true,true,true,true,true,true,false,true,true,true,true,true,true,true,true,false,true,true,true,true,true,true,true,false,false,true,true,true,true,false,true,false,true,true,true,false,false,true,true,true,true,false,true,true,true,true,true,true,false,false,false,true,true,true,true,false,false,true,true,false,true,true,false,true,true,true,false,true,true,true,true,false,true,true,true,false,true],[false,false,true],[false,true],[false,true],[true],[false,true,true,false,true,true],[true,false,true],[true,true,false,false,true],[false,true],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[false,false,true]]⟩ : Config) := by
    change (⟨_,_,_⟩ : Config) = ⟨_,_,_⟩
    congr 1; funext k; fin_cases k <;> decide +kernel
  simpa only [hi,ho] using source 0 g pk true [true,false,true] (((1 : ZMod 3),2),(0,1,1,2))
#print axioms q3_true_distinct_full_state

/-- Independent complete-state underflow fixture retains both commitments,
all original prefixes and private context while adding the canonical d prefix. -/
theorem q3_false_distinct_full_state :
    Prod.fst <$> BitOracleMachine.run code (clock 3) (start ![[false,false,true],[],[true,true],[false,true],[],[],[true,true,true],[true,true,false,false,true],[],[],[false],[true,false,true],[true,true,false,false,true],[true],[true,true,true,false,true,false,true,true,true,true,false,true,true,true,true,true,true,false,true,true,true,true,true,true,true,true,false,true,true,true,true,true,true,true,false,false,true,true,true,true,false,true,false,true,true,true,false,false,true,true,true,true,false,true,true,true,true,true,true,false,false,false,true,true,true,true,false,false,true,true,false,true,true,false,true,true,true,false,true,false,true,true,false,true,true,true,false,true],[false,false,true],[false,true],[false,true],[false],[false,true,true,false,true,true],[true,false,true],[true,true,false,false,true],[false,true],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[false,false,true]]) =
      pure (⟨none,2,![[false,false,true],[true,true,false,false,true],[true,true],[false,true],[],[],[true,true,true],[true,true,false,false,true],[],[],[false],[true,false,true],[true,true,false,false,true],[true],[true,true,true,false,true,false,true,true,true,true,false,true,true,true,true,true,true,false,true,true,true,true,true,true,true,true,false,true,true,true,true,true,true,true,false,false,true,true,true,true,false,true,false,true,true,true,false,false,true,true,true,true,false,true,true,true,true,true,true,false,false,false,true,true,true,true,false,false,true,true,false,true,true,false,true,true,true,false,true,false,true,true,false,true,true,true,false,true],[false,false,true],[false,true],[false,true],[false],[false,true,true,false,true,true],[true,false,true],[true,true,false,false,true],[false,true],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[false,false,true]]⟩ : Config) := by
  have hi : (PrimeSimCommitPairCaller.sourceResult 0 g pk false [true,false,true] (((1 : ZMod 3),2),(0,1,2,2))).stk = ![[false,false,true],[],[true,true],[false,true],[],[],[true,true,true],[true,true,false,false,true],[],[],[false],[true,false,true],[true,true,false,false,true],[true],[true,true,true,false,true,false,true,true,true,true,false,true,true,true,true,true,true,false,true,true,true,true,true,true,true,true,false,true,true,true,true,true,true,true,false,false,true,true,true,true,false,true,false,true,true,true,false,false,true,true,true,true,false,true,true,true,true,true,true,false,false,false,true,true,true,true,false,false,true,true,false,true,true,false,true,true,true,false,true,false,true,true,false,true,true,true,false,true],[false,false,true],[false,true],[false,true],[false],[false,true,true,false,true,true],[true,false,true],[true,true,false,false,true],[false,true],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[false,false,true]] := by decide +kernel
  have ho : sourceResult 0 g pk false [true,false,true] (((1 : ZMod 3),2),(0,1,2,2)) = (⟨none,2,![[false,false,true],[true,true,false,false,true],[true,true],[false,true],[],[],[true,true,true],[true,true,false,false,true],[],[],[false],[true,false,true],[true,true,false,false,true],[true],[true,true,true,false,true,false,true,true,true,true,false,true,true,true,true,true,true,false,true,true,true,true,true,true,true,true,false,true,true,true,true,true,true,true,false,false,true,true,true,true,false,true,false,true,true,true,false,false,true,true,true,true,false,true,true,true,true,true,true,false,false,false,true,true,true,true,false,false,true,true,false,true,true,false,true,true,true,false,true,false,true,true,false,true,true,true,false,true],[false,false,true],[false,true],[false,true],[false],[false,true,true,false,true,true],[true,false,true],[true,true,false,false,true],[false,true],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[false,false,true]]⟩ : Config) := by
    change (⟨_,_,_⟩ : Config) = ⟨_,_,_⟩
    congr 1; funext k; fin_cases k <;> decide +kernel
  simpa only [hi,ho] using source 0 g pk false [true,false,true] (((1 : ZMod 3),2),(0,1,2,2))
#print axioms q3_false_distinct_full_state
end ExplainableCrypto.Helios.Computational.PrimeSimDifferenceControls
