import ExplainableCrypto.Helios.Symbolic.SourceActiveBinding
import ExplainableCrypto.Helios.Symbolic.SourceExtendedExports

namespace ExplainableCrypto.Helios.Symbolic.Historical.General.Source.Extended
variable {V : Type} {n : Nat}

/-- Plain parallel congruence is derived through the extended presentation. -/
theorem Structural.plain_par {p p' q q' : Agent V}
    (hp : Structural (.plain p) (.plain p')) (hq : Structural (.plain q) (.plain q')) :
    Structural (.plain (.par p q)) (.plain (.par p' q')) :=
  (Structural.plainPar _ _).trans ((Structural.parLeft _ hp).trans
    ((Structural.parRight _ hq).trans (Structural.plainPar _ _).symm))

/-- Every previously used parallel equivalence is generated by the explicit
extended-source structural rules. -/
theorem parEq_derivable {p q : Agent V} (h : Agent.ParEq p q) :
    Structural (.plain p) (.plain q) := by
  induction h with
  | refl p => exact .refl _
  | symm _ ih => exact ih.symm
  | trans _ _ ih ih' => exact ih.trans ih'
  | zero p => exact (Structural.plainPar _ _).trans (.zero _)
  | comm p q => exact (Structural.plainPar _ _).trans ((Structural.comm _ _).trans (Structural.plainPar _ _).symm)
  | par _ _ ih ih' => exact ih.plain_par ih'
  | assoc p q r =>
    exact (Structural.plainPar _ _).trans
      ((Structural.parLeft _ (Structural.plainPar _ _)).trans
        ((Structural.assoc _ _ _).trans
          ((Structural.parRight _ (Structural.plainPar _ _).symm).trans (Structural.plainPar _ _).symm)))

/-- All evaluated internal reductions modulo parallel structure are derived
from atomic source communication and explicit active-variable structural rules. -/
theorem tau_derivable {p q : Agent Empty} (h : Agent.Tau p q) :
    Reduction (.plain p) (.plain q) := by
  obtain ⟨p',q',hp,hc,hq⟩ := h
  exact .congr (parEq_derivable hp) (coreStep_derivable hc) (parEq_derivable hq)

/-- Every historical internal stage transition has a derivation in the
variable/active fragment. The extended-source converse and name-scope layer
remain separate obligations. -/
theorem residual_internal_derivable (ns : Names n) (swap : Bool) (left right : CandidateSubstitution n Empty)
    (extra : Nat) (ch : Channels) {p q : Process.Phase}
    (h : Process.Step ns swap left right extra p .tau q) :
    Reduction (.plain (residual ns swap left right extra ch p))
      (.plain (residual ns swap left right extra ch q)) :=
  tau_derivable (residual_tau_step ns swap left right extra ch h)
end ExplainableCrypto.Helios.Symbolic.Historical.General.Source.Extended
